package org.solarsystem.web.service;

public enum PlanetName {
    SUN,MERCURY,VENUS,EARTH,MARS,JUPITER,SATURN,URANUS,NEPTUNE,PLUTO,
    MOON,
    PHOBOS,DEIMOS,
    IO,EUROPA,GANYMEDE,CALLISTO,AMALTHEA,HIMALIA,ELARA,PASIPHAE,SINOPE,LYSITHEA,CARME,ANANKE,LEDA,THEBE,ADRASTEA,METIS,CALLIRRHOE,THEMISTO,MAGACLITE,TAYGETE,CHALDENE,
    TITAN,JANUS,PROMETHEUS,PANDORA,RHEA,
    TITANIA,OBERON,
    TRITON,NEREID,LARISSA,
    CHARON,NIX,HYDRA;
}
